### ISSUE TITLE
Tests break due to #444 in version 3.2.1

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#455] opened 2021-05-05 19:28 UTC
After updating to version 3.2.1, my tests fail due to the following new function,

https://github.com/mbraak/django-file-form/blob/8c5868c1db81c460775c3f88099bdbe92747d474/django_file_form/fields.py#L58-L60

which triggers error

```
       TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

if the field is passed with data `None` (no file specified).

I am not sure what is the motivation for this piece of code since the `super()` class `FileField` accepts 

```
super().clean(data, initial)
```

**Comment by mbraak** [comment] 2021-05-06 04:48
I'll have a look.

Can you tell me more about the test? Is it a selenium test or a unit test?

**Comment by BoPeng** [comment] 2021-05-06 05:13
In my case I have a  form

```python
class MyForm(FileFormMixin):
    main_notebook = UploadedFileField(required=False, accept='.ipynb')
    attachments = MultipleUploadedFileField(required=False)
```
and I have been testing the fields with

```python
    form = MyForm(data=dict(
        main_notebook=None,
        attachments=[],
    )
    assert form.is_valid()
```
among other fields. The test stopped working with the new `MultipleUploadedFileField.clean()` function. I tried both `None` and `[]` for both fields.

**Comment by mbraak** [comment] 2021-05-06 05:59
Thanks. I added a pr to fix the test: #456

I could not reproduce the original error. The pr contains a test, but it succeeds with and without the change.

One thing I noticed about the test code above. The class `MyForm` doesn't descend from `Form`. I would expect: `class MyForm(FileFormMixin, Form)`

**Comment by mbraak** [comment] 2021-05-06 05:59
I will look for a way to test the form with `UploadedFile` and `PlaceholderUploadedFile`

**Comment by BoPeng** [comment] 2021-05-06 07:08
Thanks. My real form and test is a lot more complicated so something else might be going on. I did trace to the `clean` function but did not try to create a test case. Anyway, I can confirm that

1. My tests pass with django-file-form 3.2.0
2. break with django-file-format 3.2.1, and
3. and pass again with the PR.

**Comment by BoPeng** [comment] 2021-05-06 14:55
Did some more experiments, I can confirm that the problem persisted (only with django-file-form=3.2.1) after stripping my form down to

```python
class MyForm(FileFormMixin, forms.Form):
    main_notebook = UploadedFileField(required=False)
    attachments = MultipleUploadedFileField(required=False)
```
and test down to
```python
def test_workflow_form():
    form = forms.MyForm(data=dict(
        main_notebook=None,
        attachments=[],
    ))
    assert form.is_valid()
```
for `django==2.2.19`, but NOT for `django==3.2.1`, so the PR would be needed for django2.

**Comment by mbraak** [comment] 2021-05-06 17:07
Ok, thanks. I will merge the pr.

**Comment by mbraak** [comment] 2021-05-07 08:57
I added an example test with an uploaded file in `test_form.py`.

```python
    def test_upload_notebook(self):
        uploaded_tus_file = UploadedTusFile(
            file=ContentFile("xyz", "test.txt"), file_id="111"
        )
        files = dict(main_notebook=uploaded_tus_file)

        form = TestForm(data=dict(), files=files)

        self.assertTrue(form.is_valid())
        self.assertEqual(form.cleaned_data["main_notebook"].name, "test.txt")
```

**Comment by mbraak** [comment] 2021-05-07 09:10
The pr is merged

**Closed by mbraak** 2021-05-07 09:10 UTC
